version: '3'

services:
  database:
    image: "mysql:${MYSQL_VERSION}"
    environment:
      MYSQL_DATABASE: "${MYSQL_APP_DATABASE_NAME:-app}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 5
      start_period: 60s
    ports:
      - "3306"
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - intranet

  app:
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    networks:
      - intranet

volumes:
  database_data:

networks:
  intranet: