services:
  app:
    environment:
      DATABASE_URL: ${DATABASE_URL}
      WEB_DOCUMENT_ROOT: /app/public
      XDEBUG_CLIENT_HOST: "host.docker.internal"
      XDEBUG_CLIENT_PORT: 9003
      XDEBUG_IDE_KEY: app
      POST_SERVICE_URL: "http://post-service"
      AUTH_TOKEN: ${AUTH_TOKEN:-}
    image: webdevops/php-nginx-dev:8.3
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    networks:
      - intranet

  post-service:
    environment:
      DATABASE_URL: ${DATABASE_URL}
      WEB_DOCUMENT_ROOT: /app/public
      XDEBUG_CLIENT_HOST: "host.docker.internal"
      XDEBUG_CLIENT_PORT: 9003
      XDEBUG_IDE_KEY: post-service
      AUTH_TOKEN: ${AUTH_TOKEN:-}
    image: webdevops/php-nginx-dev:8.3
    volumes:
      - ./post-service:/app
    ports:
      - 8081:80
    networks:
      - intranet

  database:
    image: "mysql:${MYSQL_VERSION}"
    environment:
      MYSQL_DATABASE: "${MYSQL_APP_DATABASE_NAME}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 5
      start_period: 60s
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - intranet

volumes:
  database_data:

networks:
  intranet: