//@no-log
POST {{baseUrl}}/api/user/login
Accept: application/json
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set('authToken', response.body.token);
%}


###

//@no-log
POST {{baseUrl}}/api/group/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Grupa z uprawnieniami"
}

###

//@no-log
POST {{baseUrl}}/api/group/search
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "term": "test",
  "limit": 5,
  "page": 1
}

###

//@no-log
PUT {{baseUrl}}/api/group/019002b8-fdca-7166-b2b2-918fe1214789/user/invite/018ff2ab-927c-7acf-a8e2-2547d48ce2ed
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

//@no-log
GET {{baseUrl}}/api/group/invites
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

//@no-log
PUT {{baseUrl}}/api/group/user/accept/019002cd-bb8f-7e9f-811d-d98cac09b98f
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

//@no-log
DELETE {{baseUrl}}/api/group/019002b8-fdca-7166-b2b2-918fe1214789/user/remove/018ff2ab-927c-7acf-a8e2-2547d48ce2ed
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

//@no-log
GET {{baseUrl}}/api/groups
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

//@no-log
DELETE {{baseUrl}}/api/group/018fe906-7a98-7c56-bcf1-e73eca0efe60
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

POST {{baseUrl}}/api/group/post/019002b8-fdca-7166-b2b2-918fe1214789
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Hello World! This is my first post!"
}

###

DELETE {{baseUrl}}/api/group/post/delete/019008df-3746-798c-b9d4-8861548ad5fd
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET {{baseUrl}}/api/group/019002b8-fdca-7166-b2b2-918fe1214789/posts
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

// microservice authorization
GET http://localhost:8081/post/group/019002b8-fdca-7166-b2b2-918fe1214789/018f11af-69c3-7875-9169-0cb221434298
Accept: application/json
Content-Type: application/json
X-My-Auth-Header: 123456789