//@no-log
POST {{baseUrl}}/api/user/login
Accept: application/json
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set('authToken', response.body.token);
%}


###

//@no-log
POST {{baseUrl}}/api/group/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Grupa testowa 1"
}

###

//@no-log
POST {{baseUrl}}/api/group/search
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "term": "test",
  "limit": 5,
  "page": 1
}

###

//@no-log
GET {{baseUrl}}/api/groups
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

//@no-log
DELETE {{baseUrl}}/api/group/018fe906-7a98-7c56-bcf1-e73eca0efe60
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}